### ISSUE TITLE
querystringify的prefix参数定义有奇异

### ISSUE THREAD

**Issue by asins** [wangz-code/querystringify-ts#3]
看ReadMe中有`qs.stringify({ foo: bar }, true); // ?foo=bar` 这样的使用方式，但在你给出的`index.d.ts`定义中却没有`prefix`为true时的定义，这导致无法在TS中正常使用`prefix=true`。

看了源码中的实例能明白这样写的原因，但在TS中最好避免这种模棱两可的定义。

**Comment by wangz-code** [comment]
> 看ReadMe中有`qs.stringify({ foo: bar }, true); // ?foo=bar` 这样的使用方式，但在你给出的`index.d.ts`定义中却没有`prefix`为true时的定义，这导致无法在TS中正常使用`prefix=true`。
> 
> 看了源码中的实例能明白这样写的原因，但在TS中最好避免这种模棱两可的定义。

好的 我改一下,   只是angualr 编译一直提示我警告, 我当时改的时候也比较匆忙, 很多参数类型定义没仔细看
